# Generated by Django 3.2.15 on 2022-08-16 14:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loginstate', '0003_customuser_diets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Celery', 'Sedano'), ('Crustacean', 'Crostacei'), ('Dairy', 'Lattosio'), ('Eggs', 'Uova'), ('Fish', 'Pesce'), ('Gluten', 'Glutine'), ('Lupine', 'Lupini'), ('Mustard', 'Senape'), ('Peanut', 'Arachidi'), ('Sesame', 'Sesamo'), ('Shellfish', 'Molluschi'), ('Soy', 'Soia'), ('Tree-nut', 'Noci'), ('Wheat', 'Frumento')], max_length=98),
        ),
    ]
