# Generated by Django 3.2.15 on 2022-08-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginstate', '0005_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='ImageUploads',
        ),
    ]
