# Generated by Django 3.2.15 on 2022-08-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginstate', '0006_rename_images_imageuploads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUploads',
            new_name='ImageUpload',
        ),
    ]
