# Generated by Django 3.2.15 on 2022-09-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginstate', '0007_rename_imageuploads_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
